language: java
jdk:
  - oraclejdk8
env:
  - ACTIVATOR_VERSION=1.3.7 \
    ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip \
    ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE} \
    PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal \
    SBT_EXECUTABLE_NAME=activator \
install:
  - wget ${ACTIVATOR_ZIP_URL}
  - unzip -q ${ACTIVATOR_ZIP_FILE}
script:
  - mvn clean install
notifications:
  email: false
branches:
  only:
  - master
scala:
   - 2.11.8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sbt
  - $HOME/.ivy
